---
title: Homework 2
author: Zhenhua Wang
output: pdf_document
---

# Problem 1
$$
1-F(x) = \int_{x-1}^\infty \phi_{\tau}(\epsilon)d\epsilon + \int_{-\infty}^{x-1}\{ \frac{\delta}{2\delta - 1}(x - \epsilon)^{-\frac{1-\delta}{\delta}} - \frac{1 - \delta}{2\delta - 1} (x - \epsilon)^{-1} \}\phi_{\tau}(\epsilon)d\epsilon
$$

$$
F(x) = 1 - \int_{x-1}^\infty \phi_{\tau}(\epsilon)d\epsilon - \int_{-\infty}^{x-1}\{ \frac{\delta}{2\delta - 1}(x - \epsilon)^{-\frac{1-\delta}{\delta}} - \frac{1 - \delta}{2\delta - 1} (x - \epsilon)^{-1} \}\phi_{\tau}(\epsilon)d\epsilon
$$

```{r message=FALSE, warning=FALSE}

```

# Problem 2
\begin{align*}
f(x; \theta)
&= \sqrt{\frac{1}{4\pi}} \frac{\text{exp}(-\frac{1}{4x} - \theta x)}{x^{3/2} \text{exp}(-\sqrt{\theta})} \\
&= \frac{\text{exp}(-\frac{1}{4x} - \theta x +\sqrt{\theta})}{4\pi x^{3/2}}
\end{align*}

Proposal distribution
$$
q(x) = 0.09 e^{-0.09x}
$$

```{r message=FALSE, warning=FALSE}
true_density <- function(x, theta = 0.1) {
  exp(-1/(4*x) - theta*x + sqrt(theta)) / (sqrt(4*pi) * x^(3/2))
}

proposal_density <- function(x) {
  0.09 * exp(-0.09 * x)
}

proposal_quantile <- function(x) {
  -log(1 - x) / 0.09
}

rejection_sampler <- function(N, K, true_dens, prop_dens, prop_quan) {
  res <- matrix(NA, 2, N)
  for (i in 1:N) {
    # Generate variable from proposal distribution
    U <- runif(1)
    exp_var <- prop_quan(U)
    counter <- 1
    # Evaluate ratio
    ratio <- true_dens(exp_var) / (K * prop_dens(exp_var))
    while (runif(1) > ratio) {
      # Generate variable from proposal distribution
      U <- runif(1)
      exp_var <- prop_quan(U)
      counter <- counter + 1
      # Update ratio
      ratio <- true_dens(exp_var) / (K * prop_dens(exp_var))
    }
    res[1, i] <- exp_var
    res[2, i] <- counter
  }
  return(res)
}

## Compute rejection factor K
N <- 100000
x_vec <- seq(1e-5, 60, length.out = N)
true_dens <- true_density(x_vec)
prop_dens <- proposal_density(x_vec)
print(sprintf("sup f(x)/q(x) is approximate to %.3f", max(true_dens / prop_dens)))
K <- 15
## sample
set.seed(5)
res <- rejection_sampler(N, K = K,
  true_dens = true_density,
  prop_dens = proposal_density,
  prop_quan = proposal_quantile)
samples <- res[1, ]
## plot
hist(samples, breaks = 1000, freq = FALSE, border = "lightblue")
curve(true_density, from = 1e-5, to = 60,
  n = 1000, add = TRUE, col = "red", lty = 3)
```

# Problem 3
```{r message=FALSE, warning=FALSE}

```

# Appendix
